#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:30:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

# run MatLab code
mkdir -p out_dir
mkdir -p out_data

matlab -nodisplay -r main

